import type { DocUpdatePlan } from "../entities/doc-update-plan";

const SEVERITY_EMOJI: Record<string, string> = {
  high: "🔴",
  medium: "🟡",
  low: "🟢",
};

export function formatPrBody(
  plan: DocUpdatePlan,
  iterationsUsed: number,
  remainingGaps: number
): string {
  const lines: string[] = [];

  lines.push("## Doc Gardener — Automated Documentation Update");
  lines.push("");
  lines.push(
    "This PR was generated by the doc-gardener agent after detecting documentation drift."
  );
  if (iterationsUsed > 1) {
    lines.push(
      `The agent used **${iterationsUsed} review iteration(s)** to refine the documentation.`
    );
  }
  if (remainingGaps > 0) {
    lines.push(
      `> **Note:** ${remainingGaps} gap(s) remain unresolved after ${iterationsUsed} iteration(s).`
    );
  }
  lines.push("");

  // Drift summary
  lines.push("### Drift Report");
  lines.push("");
  lines.push("| Severity | Type | Source | File | Detail |");
  lines.push("|----------|------|--------|------|--------|");

  for (const item of plan.driftItems) {
    const sev = `${SEVERITY_EMOJI[item.severity] ?? ""} ${item.severity}`;
    const source = item.source === "llm" ? "semantic" : "deterministic";
    lines.push(
      `| ${sev} | ${item.driftType} | ${source} | \`${item.file}\` | ${item.detail} |`
    );
  }

  lines.push("");

  // Semantic drift details
  const semanticItems = plan.driftItems.filter((d) => d.source === "llm");
  if (semanticItems.length > 0) {
    lines.push("### Semantic Drift Details");
    lines.push("");
    for (const item of semanticItems) {
      lines.push(`- **${item.claim ?? item.detail}**`);
      if (item.codeEvidence) {
        lines.push(`  - Evidence: ${item.codeEvidence}`);
      }
      if (item.reasoning) {
        lines.push(`  - Reasoning: ${item.reasoning}`);
      }
      if (item.confidence !== undefined) {
        lines.push(`  - Confidence: ${(item.confidence * 100).toFixed(0)}%`);
      }
    }
    lines.push("");
  }

  // Policy rules applied
  if (plan.policyRules.length > 0) {
    lines.push("### Policy Rules Applied");
    lines.push("");
    for (const rule of plan.policyRules) {
      lines.push(
        `- **[${rule.scope}]** ${rule.rule} _(confidence: ${rule.confidence})_`
      );
    }
    lines.push("");
  }

  // Fixes applied
  lines.push("### Fixes Applied");
  lines.push("");
  for (const fix of plan.fixes) {
    lines.push(
      `- **${fix.action}** \`${fix.file}\`${fix.section ? ` § ${fix.section}` : ""}: ${fix.description}`
    );
  }

  if (plan.planReasoning) {
    lines.push("");
    lines.push(`### Plan Reasoning`);
    lines.push("");
    lines.push(plan.planReasoning);
  }

  lines.push("");
  lines.push("---");
  lines.push(
    "_Generated by [@tilsley/doc-gardener](https://github.com/tilsley/agents)_"
  );

  return lines.join("\n");
}
